baseURL = "/"
languageCode = "en"
defaultContentLanguage = "zh-cn"                             # en / zh-cn / ... (This field determines which i18n file to use)
title = "言中医 - 中医学习和入门"
preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
theme = "even"


paginate = 10                                              # 首页每页显示的文章数
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = "言中医"            # default: author.name ↓        # 默认为下面配置的author.name ↓

[author]                  # essential                     # 必需
  name = "良言"

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu              # 配置目录
  name = "主页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "分类"
  weight = 40
  identifier = "categories"
  url = "/categories/"

[params]
  version = "4.x"           # Used to give a friendly message when you have an incompatible update

  since = "2019"            # Site creation time          # 站点建立时间

  # site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle = "言中医"        # default: the title value    # 默认值: 上面设置的title值
  keywords = ["Hugo", "中医学习","中医入门"]
  description = "中医知识学习和入门小站"

  # paginate of archives, tags and categories             # 归档、标签、分类每页显示的文章数目，建议修改为一个较大的值
  archivePaginate = 10


  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # show word count and read time ?                       # 是否显示字数统计与阅读时间
  moreMeta = true


  # 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true                                                                            # 是否开启目录
  autoCollapseToc = false   # Auto expand and collapse toc                              # 目录自动展开/折叠
  fancybox = true           # see https://github.com/fancyapps/fancybox                 # 是否启用fancybox（图片可点击）


  [params.social]                                         # 社交链接
    a-email = "mailto:zhongyixuexi@outlook.com"





